### ISSUE TITLE
Add text input for other

### ISSUE THREAD

**Issue by gozzilli** [PhilGrunewald/MeterApp#1]
Add text input for "other" button

**Comment by gozzilli** [comment]
@PhilGrunewald is this still valid? Do we want text input in some circumstances?

**Comment by PhilGrunewald** [comment]
I think that would be a great 'catch all' option. From my early trial experience, it can be quite frustrating if you just can't find what you are doing.

**Comment by gozzilli** [comment]
Agreed. From my current dev experience, it will be a pain in the arse :-) (excuse my French)
