### ISSUE TITLE
Log activity list

### ISSUE THREAD

**Issue by gozzilli** [PhilGrunewald/MeterApp#12]
![img_20160310_120617](https://cloud.githubusercontent.com/assets/1502267/13669111/36fee742-e6b9-11e5-9741-9cd6cfd6eba7.jpg)

**Comment by gozzilli** [comment]
`tuc_log.txt` should be renamed to `debug.csv`  
`activity.log` -> `activity.csv`  
`survey.log` -> `survey.csv`

**Comment by PhilGrunewald** [comment]
all done
