### ISSUE TITLE
Format time in activity time picker

### ISSUE THREAD

**Issue by gozzilli** [PhilGrunewald/MeterApp#14]
Or any other strings coming from the json structure

**Comment by PhilGrunewald** [comment]
Purpose:
1) When, at 14:27, clicking a button to say I did this activity "15 minutes ago" we can display "at 14:12" underneath
2) When writing the activity.csv file we can note "reported time: 14:27" and activity time: "14:12"

**Comment by gozzilli** [comment]
Working on this and a few other things now. Everything unassigned is a potential candidate ;-)
