### ISSUE TITLE
Second time round, category colour doesn't show

### ISSUE THREAD

**Issue by gozzilli** [PhilGrunewald/MeterApp#20]

**Comment by PhilGrunewald** [comment]
I think I found the problem: we keep adding on class definitions on every round:
`class ="btn-activity col care_self other_category"`
I think we need to reset to 
`class ="btn-activity col"`
before adding the category class...

**Comment by gozzilli** [comment]
That's what lines 188-192 do though (or should do):

```
             CATEGORIES.forEach(function (cat) {
                 app.actionButtons.each(function (button) {
                     $(button).removeClass(cat);
                 });
             });
```

Maybe `other_category` is always added anyway?

Careful if you reset it to `class ="btn-activity col"` because then if 
we change the HTML we need to remember to change the JS too..

**Comment by PhilGrunewald** [comment]
And they do.
I changed l.228 in index.js
`button.addClass(activity.category || "other_category");`
to
`button.addClass(activity.category);`
and now all seems fine - must admit that I am not sure what the || bit was for - so I hope I haven't broken something else..
