### ISSUE TITLE
Cordova screwed up after pulling code from @gozzilli 

### ISSUE THREAD

**Issue by PhilGrunewald** [PhilGrunewald/MeterApp#22]
We should compare our .gitignore files.

I keep having to uninstall and reinstall packages to get cordova to work after pulling code from you @gozzilli

**Comment by gozzilli** [comment]
@PhilGrunewald you have removed `config.xml` in commit 21a55aa35c13bd5aa31718cf52a0777c89694aaf
This really does break the cordova project!
