### ISSUE TITLE
Rainforest Automation Connection

### ISSUE THREAD

**Issue by mattm401** [PhilGrunewald/MeterApp#25]
Setup US Dev Database and develop component for acquiring smart meter data from specified meter via Rainforest Automation cloud.

- [ ] Setup a US Database; modify METER to point to it using a new "language US" flag.

- [x] Add to connection js the additional infrastructure necessary to poll for data from the Rainforest Automation Cloud.

- [ ] Figure out how to establish connections with Cloud robustly; per household.

**Comment by mattm401** [comment]
@PhilGrunewald Perhaps it make sense to keep the database schema files in a folder here if we're going to be sharing updates. Not sure if the scripts have anything you wouldn't want shared, but maybe those could be included as well. If there are passwords and specific connection information, perhaps you can scrub those details?

**Comment by PhilGrunewald** [comment]
The schema is now in /docs/19_01_MeterSchema.sql
We can add a little content to that...

**Comment by mattm401** [comment]
Probably better to keep issues in my fork, I think.
