### ISSUE TITLE
Android 9+ ClearText network error

### ISSUE THREAD

**Issue by adrianomatousek** [PhilGrunewald/MeterApp#34]
**Issue:**
ClearText error on Android 9 device.

![image](https://user-images.githubusercontent.com/28990013/81957654-ce18f880-9604-11ea-81e7-23ce8866f800.png)

Error is also visible in console when inspecting and seems like it's not limited to just the consent page. This means it might not be sending data to the server.

Android 9+ disables ClearText traffic by default: https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted

**Possible fixes:**
1. Change all url calls to https and add https support to the server
or
2. If cleartext traffic is desired, you can add the following to the `<platform name="android">...</platform>` tag which is in `config.xml`. 

```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
    <application android:usesCleartextTraffic="true" />
</edit-config>
```

Then also define the namespace by appending the following as an attribute to the `<widget ...>` tag at the top of the file: `xmlns:android="http://schemas.android.com/apk/res/android"`

**Comment by PhilGrunewald** [comment]
Thanks for flagging that up, Adriano!
www.energy-use.org supports https, so I simply changed all the URLs from http to https.
It is submitted to Google Play. Once it comes out, it would be great if you could give it a test ride.
Many thanks,
Phil

**Comment by adrianomatousek** [comment]
Great! I've tested on my Android device using the source code and it works, no more errors! When I tested on an emulated Android device there was a side effect of the 'About you' button on the Main Menu being invisible. But on my physical device everything was working. I will test out the Google Play release too incase that somehow affects it.

**Comment by adrianomatousek** [comment]
The Google Play store release works on my Android 9 phone.

I noticed one more http url on line 3012 of the server-side file `www.energy-use.org/app/help/help.js` which is referencing the `intro.mp4`.

**Comment by PhilGrunewald** [comment]
Hi Adriano,
Thanks so much for testing - I owe you a drink!
Good spot! I changed that landing page into a simple html page now: https://www.energy-use.org/app/help/help.html
I hope that solves the issue.

**Comment by adrianomatousek** [comment]
Yes that solved it and it works well through the app!
