### ISSUE TITLE
When activity input is completed, return to HOME

### ISSUE THREAD

**Issue by gozzilli** [PhilGrunewald/MeterApp#7]
Consider:
- enjoyment screen
- location screen
- time screen (might not be necessary)

**Comment by PhilGrunewald** [comment]
I can't remember what naming convention we decided on. Something like:

"home" - the screen that lists recorded activities and the "add new" button
"activity root" - the first activity screen with Care / Work /Leisure / Food / Travel and More...
"survey root" - the first survey screen

All 'enjoyment' choices point to 
    "next":  "home"

**Comment by gozzilli** [comment]
Yes I think this is correct.

**Comment by PhilGrunewald** [comment]
screen now set to "home", "activity root" and "survey root"
